[test_internal]
type = "internal"
description = "to test an internal command"

[test_redirect]
type = "redirect"
url = "http://some.url.tld/search?q="
description = "to test a redirect command"

[test_redirect_fmt]
type = "redirect"
url = "http://some.url.tld/search?q=\"{query}\""
description = "to test a redirect command with a formatted URL"
