name: lint + tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # to use this repository's private action,
      # we must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        uses: ./actions/tests/
