name: lint + tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build test image
        run: docker build --tag test/winston:latest --build-arg action=test .
        shell: bash
  run-tests:
    runs-on: ubuntu-latest
    needs: build-test-image
    steps:
      - name: Run tests container
        run: docker run --rm -v $(pwd):/github/workspace --workdir /github/workspace test/winston:latest
        shell: bash
  build-production-image:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Build production image
        run: docker build --tag production/winston:latest --build-arg action=production .
        shell: bash
      - name: Tag production image
        run: docker tag production/winston:latest production/winston:production
        shell: bash
