name: build

on:
  push:
    branches: [ main, test-workflow* ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build test image
        run: docker build --tag test/winston:latest --build-arg action=test .
        shell: bash
      - name: Run tests container
        run: docker run --rm -v $(pwd):/github/workspace --workdir /github/workspace test/winston:latest
        shell: bash
  build-production-image:
    runs-on: ubuntu-latest
    needs: run-tests
    outputs:
      image_id: ${{ steps.image_id.outputs.image_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build production image
        run: docker build --tag production/winston:latest --build-arg action=production .
        shell: bash
      - name: Get image ID
        id: image_id
        run: echo "::set-output name=image_id::$(docker images -q production/winston:latest)"
        shell: bash
  tag-production-image:
    runs-on: ubuntu-latest
    needs: build-production-image
    steps:
      - name: Tag production image
        run: docker tag ${{needs.build-production-image.outputs.image_id}} production/winston:production
        shell: bash
